preset1:
  image: 'gantry-admin://images/preset1.jpg'
  description: GANTRY5_PLATFORM_PRESET1
  colors:
    - '#0071bc' #dominant
    - '#e31c3d' #accent 1 contrast dominant
    - '#9bdaf1' #accent 2 Light
    - '#112e51' #accent 3 Dark Dominant
    - '#ffffff' #body (base) background
    - '#212121' #body (base) text 

  styles:
    base:
      dominant-color: '#0071bc'
      text-color: '#212121'
      background: '#ffffff'
      background-image: ''
      content-margin: 0.5rem
      content-padding: 0.5rem
    accent:
      color-1: '#e31c3d'
      color-2: '#9bdaf1'
      color-3: '#112e51'
    font:
      family-default: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
      family-title: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
      family-quote: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
    zenith:
      section-preset: disabled
      text-color: '#ffffff'
      link-color: '#0071bc'
      background: '#000000'
    navtop:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#0071bc'
      background: '#ffffff'
    navigation:
      text-color: '#ffffff'
      link-color: '#ffffff'
      background: '#0071bc'
    header3:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#0071bc'
      background: '#ffffff'
    intro:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#0071bc'
      background: '#ffffff'
    features:
      section-preset: accent2
      text-color: '#ffffff'
      link-color: '#0071bc'
      background: '#ffffff'
    utility:
      section-preset: accent3
      text-color: '#212121'
      link-color: '#0071bc'
      background: '#ffffff'
    above:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#0071bc'
      background: '#ffffff'
    testimonials:
      section-preset: accent3
      text-color: '#212121'
      link-color: '#0071bc'
      background: '#ffffff'
    expanded:
      section-preset: base
      text-color: '#ffffff'
      link-color: '#0071bc'
      background: '#ffffff'
    mainbottom:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#0071bc'
      background: '#ffffff'
    footertop:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#0071bc'
      background: '#ffffff'
    footer:
      section-preset: accent3
      text-color: '#ffffff'
      link-color: '#9bdaf1'
      background: '#ffffff'
    footerbottom:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#0071bc'
      background: '#ffffff'
    nadir:
      section-preset: disabled
      text-color: '#ffffff'
      link-color: '#0071bc'
      background: '#000000'
    offcanvas:
      background: '#0071bc'
      text-color: '#eceeef'
      toggle-color: '#ffffff'
preset2:
  image: 'gantry-admin://images/preset2.jpg'
  description: GANTRY5_PLATFORM_PRESET2
  colors:
    - '#4caf50' #dominant
    - '#448aff' #accent 1 contrast dominant
    - '#c8e6c9' #accent 2 Light
    - '#388e3c' #accent 3 Dark Dominant
    - '#ffffff' #body (base) background
    - '#212121' #body (base) text 

  styles:
    base:
      dominant-color: '#4caf50'
      text-color: '#212121'
      background: '#ffffff'
      background-image: ''
      content-margin: 0.5rem
      content-padding: 0.5rem
    accent:
      color-1: '#448aff'
      color-2: '#c8e6c9'
      color-3: '#388e3c'
    font:
      family-default: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
      family-title: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
      family-quote: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
    zenith:
      section-preset: disabled
      text-color: '#ffffff'
      link-color: '#4caf50'
      background: '#000000'
    navtop:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#4caf50'
      background: '#ffffff'
    navigation:
      text-color: '#ffffff'
      link-color: '#ffffff'
      background: '#4caf50'
    header:
      section-preset: accent3
      text-color: '#212121'
      link-color: '#4caf50'
      background: '#ffffff'
    intro:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#4caf50'
      background: '#ffffff'
    features:
      section-preset: accent2
      text-color: '#ffffff'
      link-color: '#4caf50'
      background: '#ffffff'
    utility:
      section-preset: accent3
      text-color: '#212121'
      link-color: '#4caf50'
      background: '#ffffff'
    above:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#4caf50'
      background: '#ffffff'
    testimonials:
      section-preset: accent3
      text-color: '#212121'
      link-color: '#4caf50'
      background: '#ffffff'
    expanded:
      section-preset: base
      text-color: '#ffffff'
      link-color: '#4caf50'
      background: '#ffffff'
    mainbottom:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#4caf50'
      background: '#ffffff'
    footertop:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#4caf50'
      background: '#ffffff'
    footer:
      section-preset: accent3
      text-color: '#ffffff'
      link-color: '#c8e6c9'
      background: '#ffffff'
    footerbottom:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#4caf50'
      background: '#ffffff'
    nadir:
      section-preset: disabled
      text-color: '#ffffff'
      link-color: '#4caf50'
      background: '#000000'
    offcanvas:
      background: '#4caf50'
      text-color: '#eceeef'
      toggle-color: '#ffffff'
preset3:
  image: 'gantry-admin://images/preset3.jpg'
  description: GANTRY5_PLATFORM_PRESET3
  colors:
    - '#8f734a' #dominant
    - '#893040' #accent 1 contrast dominant
    - '#d1b379' #accent 2 Light
    - '#314159' #accent 3 Dark Dominant
    - '#ffffff' #body (base) background
    - '#212121' #body (base) text 

  styles:
    base:
      dominant-color: '#8f734a'
      text-color: '#212121'
      background: '#ffffff'
      background-image: ''
      content-margin: 0.5rem
      content-padding: 0.5rem
    accent:
      color-1: '#893040'
      color-2: '#d1b379'
      color-3: '#314159'
    font:
      family-default: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
      family-title: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
      family-quote: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
    zenith:
      section-preset: disabled
      text-color: '#ffffff'
      link-color: '#8f734a'
      background: '#000000'
    navtop:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#8f734a'
      background: '#ffffff'
    navigation:
      text-color: '#ffffff'
      link-color: '#ffffff'
      background: '#8f734a'
    header:
      section-preset: accent3
      text-color: '#212121'
      link-color: '#8f734a'
      background: '#ffffff'
    intro:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#8f734a'
      background: '#ffffff'
    features:
      section-preset: accent2
      text-color: '#ffffff'
      link-color: '#8f734a'
      background: '#ffffff'
    utility:
      section-preset: accent3
      text-color: '#212121'
      link-color: '#8f734a'
      background: '#ffffff'
    above:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#8f734a'
      background: '#ffffff'
    testimonials:
      section-preset: accent3
      text-color: '#212121'
      link-color: '#8f734a'
      background: '#ffffff'
    expanded:
      section-preset: base
      text-color: '#ffffff'
      link-color: '#8f734a'
      background: '#ffffff'
    mainbottom:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#8f734a'
      background: '#ffffff'
    footertop:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#8f734a'
      background: '#ffffff'
    footer:
      section-preset: accent3
      text-color: '#ffffff'
      link-color: '#d1b379'
      background: '#ffffff'
    footerbottom:
      section-preset: accent2
      text-color: '#212121'
      link-color: '#8f734a'
      background: '#ffffff'
    nadir:
      section-preset: disabled
      text-color: '#ffffff'
      link-color: '#8f734a'
      background: '#000000'
    offcanvas:
      background: '#8f734a'
      text-color: '#eceeef'
      toggle-color: '#ffffff'
preset4:
  image: 'gantry-admin://images/preset4.jpg'
  description: GANTRY5_PLATFORM_PRESET4
  colors:
    - '#ebb800' #dominant
    - '#000000' #accent 1 contrast dominant
    - '#787878' #accent 2 Light
    - '#000000' #accent 3 Dark Dominant
    - '#333333' #body (base) background
    - '#dedede' #body (base) text 

  styles:
    base:
      dominant-color: '#ebb800'
      text-color: '#dedede'
      background: '#333333'
      background-image: ''
      content-margin: 0.5rem
      content-padding: 0.5rem
    accent:
      color-1: '#000000'
      color-2: '#787878'
      color-3: '#000000'
    font:
      family-default: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
      family-title: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
      family-quote: 'Lato, Helvetica, Tahoma, Geneva, Arial, sans-serif'
    zenith:
      section-preset: disabled
      text-color: '#ffffff'
      link-color: '#ebb800'
      background: '#000000'
    navtop:
      section-preset: accent2
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    navigation:
      text-color: '#333333'
      link-color: '#333333'
      background: '#ebb800'
    header:
      section-preset: accent3
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    intro:
      section-preset: accent2
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    features:
      section-preset: accent2
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    utility:
      section-preset: accent3
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    above:
      section-preset: accent2
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    testimonials:
      section-preset: accent3
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    expanded:
      section-preset: base
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    mainbottom:
      section-preset: accent2
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    footertop:
      section-preset: accent2
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    footer:
      section-preset: accent3
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    footerbottom:
      section-preset: accent2
      text-color: '#dedede'
      link-color: '#ebb800'
      background: '#333333'
    nadir:
      section-preset: disabled
      text-color: '#ffffff'
      link-color: '#ebb800'
      background: '#000000'
    offcanvas:
      background: '#ebb800'
      text-color: '#eceeef'
      toggle-color: '#ffffff'